-- MySQL Script generated by MySQL Workbench
-- Sat Jan  6 18:38:05 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema yii_shop
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `yii_shop` ;

-- -----------------------------------------------------
-- Schema yii_shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `yii_shop` DEFAULT CHARACTER SET utf8 ;
USE `yii_shop` ;

-- -----------------------------------------------------
-- Table `yii_shop`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yii_shop`.`category` ;

CREATE TABLE IF NOT EXISTS `yii_shop`.`category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `create_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `yii_shop`.`user_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yii_shop`.`user_group` ;

CREATE TABLE IF NOT EXISTS `yii_shop`.`user_group` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL DEFAULT NULL,
  `create_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `yii_shop`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yii_shop`.`user` ;

CREATE TABLE IF NOT EXISTS `yii_shop`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `groups_id` INT(11) NULL DEFAULT NULL,
  `username` VARCHAR(32) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `salt` VARCHAR(255) NOT NULL,
  `access_token` VARCHAR(255) NULL,
  `name` VARCHAR(32) NULL,
  `surname` VARCHAR(32) NULL DEFAULT NULL,
  `email` VARCHAR(64) NULL DEFAULT NULL,
  `phone` VARCHAR(64) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `create_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`username` ASC),
  INDEX `fk_users_groups_id_idx` (`groups_id` ASC),
  CONSTRAINT `fk_user_groups_id`
    FOREIGN KEY (`groups_id`)
    REFERENCES `yii_shop`.`user_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `yii_shop`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yii_shop`.`product` ;

CREATE TABLE IF NOT EXISTS `yii_shop`.`product` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `category_id` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `photo` VARCHAR(255) NULL DEFAULT NULL,
  `short_description` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  `create_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_product_category_id_idx` (`category_id` ASC),
  CONSTRAINT `fk_product_category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `yii_shop`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `yii_shop`.`feedback`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yii_shop`.`feedback` ;

CREATE TABLE IF NOT EXISTS `yii_shop`.`feedback` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL DEFAULT NULL,
  `product_id` INT(11) NULL DEFAULT NULL,
  `text` TEXT NULL DEFAULT NULL,
  `create_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_feedback_used_id_idx` (`user_id` ASC),
  INDEX `fk_feedback_product_id_idx` (`product_id` ASC),
  CONSTRAINT `fk_feedback_used_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `yii_shop`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_feedback_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `yii_shop`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `yii_shop`.`session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yii_shop`.`session` ;

CREATE TABLE IF NOT EXISTS `yii_shop`.`session` (
  `sid` VARCHAR(64) NOT NULL,
  `user_id` INT(11) NULL DEFAULT NULL,
  `last_update` DATETIME NULL DEFAULT NULL,
  `create_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`sid`),
  INDEX `fk_sessions_user_id_idx` (`user_id` ASC),
  UNIQUE INDEX `sid_UNIQUE` (`sid` ASC),
  CONSTRAINT `fk_session_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `yii_shop`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
